# Generated by Django 6.0.3 on 2026-03-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(help_text='Emoji icon for the category', max_length=10)),
                ('count', models.PositiveIntegerField(default=0, help_text='Number of items in category')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(max_length=100)),
                ('image', models.CharField(help_text='Relative path inside static, e.g. store/images/product_watch.png', max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tag', models.CharField(choices=[('new', 'New'), ('best', 'Best Seller'), ('sale', 'On Sale')], default='new', max_length=10)),
                ('badge', models.CharField(blank=True, help_text='Badge text, e.g. New, -30%, Hot', max_length=20)),
                ('badge_class', models.CharField(blank=True, choices=[('new', 'New'), ('sale', 'Sale'), ('hot', 'Hot')], max_length=10)),
                ('stars', models.CharField(default='★★★★★', max_length=20)),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
